base_image: centos:7
context_dir: images/prune-ocp-projects
failed_jobs_history_limit: "5"
job_name: cronjob-prune-projects
job_service_account: pruner
name: prune-ocp-projects
namespace: cluster-ops
project_exclude_system: management-infra istio-system cluster-ops
project_exclude_user: '# TODO: must define a default value for .project_exclude_user'
schedule: '@hourly'
source_repository_ref: master
source_repository_url: https://github.com/redhat-cop/openshift-management
success_jobs_history_limit: "5"
tag: latest
timestamp_hours_ago: -12hours
