apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    template: cronjob-ldap-group-sync-secure
  name: {{ .Values.job_name }}
  namespace: {{ .Values.namespace }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ .Values.failed_jobs_history_limit }}
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          activeDeadlineSeconds: 500
          containers:
          - command:
            - /bin/bash
            - -c
            - oc adm groups sync --confirm --sync-config=/ldap-sync/config/ldap-group-sync.yaml
              $([ -s /ldap-sync/config/whitelist.txt ] && echo --whitelist=/ldap-sync/config/whitelist.txt)
            image: {{ .Values.image }}:{{ .Values.image_tag }}
            name: {{ .Values.job_name }}
            volumeMounts:
            - mountPath: /ldap-sync/config
              name: ldap-sync-config
            - mountPath: /ldap-sync/ca
              name: ldap-sync-ca
            - mountPath: /ldap-sync/secrets
              name: ldap-bind-password
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          serviceAccount: {{ .Values.job_service_account }}
          serviceAccountName: {{ .Values.job_service_account }}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              name: {{ .Values.ldap_sync_configmap }}
            name: ldap-sync-config
          - configMap:
              name: {{ .Values.ldap_sync_ca_configmap }}
            name: ldap-sync-ca
          - name: ldap-bind-password
            secret:
              secretName: {{ .Values.ldap_bind_password_secret }}
  schedule: "{{ .Values.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.success_jobs_history_limit }}
