enable_affinity_violation: "False"
enable_utilization: "False"
image: registry.access.redhat.com/openshift3/ose-descheduler
image_tag: v3.11
max_cpu: "0"
max_mem: "0"
max_pods: "0"
min_cpu: "0"
min_mem: "0"
min_pods: "0"
namespace: kube-system
node_threshold: "0"
remove_dups: "False"
schedule: '@hourly'
