apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    description: Defines how to build the application
  labels:
    template: cronjob-aws-ocp-snap
  name: {{ .Values.name }}
spec:
  completionDeadlineSeconds: "1800"
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.name }}:latest
  runPolicy: Serial
  source:
    contextDir: /images/cronjob-aws-ocp-snap
    git:
      uri: https://github.com/redhat-cop/openshift-management.git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: centos:7
    type: Docker
  triggers:
  - type: ConfigChange
