name: gitlab-cleanup

image:
  name: "quay.io/mcanoy/gitlab-cleanup" # "quay.io/rht-labs/omp-gitlab-cleanup"
  tag: "master" # This is intended to be overridden by the parent Helm chart.

generateSecret: false # set true if you want to create the secret data file.

env:
  secret:
    name: secret-gitlab-info # cronjob references this secret
    personalAccessToken: xxxx # real value needed if useSecret=true
  gitlabApiUrl: http://gitlab.ca # real value needed if useSecret=true
  parentGroupId: 6 # real value needed if useSecret=true
  deleteAfterInHours: 876000
  dryRun: TRUE
  logLevel: DEBUG

cron:
  schedule: "1 0 * * *"
  historyLimit: 5
