apiVersion: v1
data:
  ldap-group-sync.yaml: |
    kind: "LDAPSyncConfig"
    apiVersion: "v1"
    url: "{{ .Values.ldap_url }}"
    insecure: true
    bindDN: "{{ .Values.ldap_bind_dn }}"
    bindPassword:
      file: "/etc/secrets/bind_password"
    rfc2307:
      groupsQuery:
        baseDN: "{{ .Values.ldap_groups_search_base }}"
        scope: "sub"
        derefAliases: "never"
        filter: "{{ .Values.ldap_groups_filter }}"
        pageSize: 0
      groupUIDAttribute: "{{ .Values.ldap_group_uid_attribute }}"
      groupNameAttributes: {{ .Values.ldap_group_name_attributes }}
      groupMembershipAttributes: {{ .Values.ldap_group_membership_attributes }}
      usersQuery:
        baseDN: "{{ .Values.ldap_users_search_base }}"
        scope: "sub"
        derefAliases: "never"
        pageSize: 0
      userNameAttributes: {{ .Values.ldap_user_name_attributes }}
      userUIDAttribute: "{{ .Values.ldap_user_uid_attribute }}"
      tolerateMemberNotFoundErrors: true
      tolerateMemberOutOfScopeErrors: true
  whitelist.txt: {{ .Values.ldap_groups_whitelist }}
kind: ConfigMap
metadata:
  labels:
    template: cronjob-ldap-group-sync
  name: ldap-config
  namespace: {{ .Values.namespace }}
